<a href="https://colab.research.google.com/github/ArunPesari2/ArunPesari2/blob/main/1_numpy_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors(more than two Dimensional arrays)

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [ ]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [ ]:
print("pi values",np.pi)

print("cos value",np.cos(90))
print("sqrt value",np.sqrt(1.334))
print("exp values",np.exp(1))
#log base e
# Natural logarithm
print("log e to the base e",np.log(np.exp(1)))
print("log e to the base 1",np.log(1))



pi values 3.141592653589793
cos value -0.4480736161291701
sqrt value 1.1549891774384728
exp values 2.718281828459045
log e to the base e 1.0
log e to the base 1 0.0


In [ ]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print("the type of vector",type(vec))

print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])

print("the type of matrix",type(mat))
print('')
print(mat)
print('')
print(mat.T)
print()

mat2= np.array([np.arange(0,5),np.arange(0,5)])
print(mat2)
print(mat2[1,1])

the type of vector <class 'numpy.ndarray'>
[1 2 3]
the type of matrix <class 'numpy.ndarray'>

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]

[[0 1 2 3 4]
 [0 1 2 3 4]]
1


In [ ]:
# there are lots of other ways to create numpy arrays
# numpy arrayRange

# In the range datatype, you will store inclusive, exclusive and step
print(type(range(0,15)))

# In this narray datatype, you will store all the elements.
vec2 = np.arange(0,15)
print(type(vec2))
print(vec2)
print('')
vec3 = np.arange(3,21,.5)
print(vec3)


<class 'range'>
<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5
 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5]


In [ ]:
# inclusive boundary on both sides
# goes from left to right
# with copy there will be no poitner reference
vec4 = np.linspace(0,5,15)
print(vec4)
print('')
print(vec4.reshape(5,3))
vec4_reshaped = vec4.reshape(3,5).copy()
print(vec4_reshaped)
vec4_reshaped[1,1]=100
print(vec4)

[0.         0.35714286 0.71428571 1.07142857 1.42857143 1.78571429
 2.14285714 2.5        2.85714286 3.21428571 3.57142857 3.92857143
 4.28571429 4.64285714 5.        ]

[[0.         0.35714286 0.71428571]
 [1.07142857 1.42857143 1.78571429]
 [2.14285714 2.5        2.85714286]
 [3.21428571 3.57142857 3.92857143]
 [4.28571429 4.64285714 5.        ]]
[[0.         0.35714286 0.71428571 1.07142857 1.42857143]
 [1.78571429 2.14285714 2.5        2.85714286 3.21428571]
 [3.57142857 3.92857143 4.28571429 4.64285714 5.        ]]
[0.         0.35714286 0.71428571 1.07142857 1.42857143 1.78571429
 2.14285714 2.5        2.85714286 3.21428571 3.57142857 3.92857143
 4.28571429 4.64285714 5.        ]


In [ ]:
# zero , one , identity
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# we can +-*/ arrays together if they're the right size
# broacasting comes ino pic when sizes are different

a= np.arange(1,5)
b= np.arange(1,6)
# print(a+b)

#broadcasting takes place here
a= np.arange(1,2)
b= np.arange(1,6)
print(a+b)

a= np.arange(1,3)
b= np.arange(1,6)
# print(a+b)

# there is whole lot of rules in broadcasting, but we focus on what's important and relevant
# addition or subtraction of vector
vec1=np.arange(1,3)
vec2=np.arange(3,5)
print(vec1)
print(vec2)
print(vec2+vec1)
print(vec2-vec1)

# dot product of a vector
# significance
print(vec2*vec1)
print((vec2*vec1).sum())

[2 3 4 5 6]
[1 2]
[3 4]
[4 6]
[2 2]
[3 8]
11


In [ ]:
# we can do matrix multiplication
# even the broadcasting comes into pic here but we are not gonna focus that
# conventional" no: of columns in left matrix = no: of rows in another matrix
print(vec)
print()

print(mat)
print('')

# we change the data state to another state for mathematical convience for building models
# for matric algebra
product = np.matmul(mat,vec)
print(product)
print()



[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[ 8 41 44]



In [ ]:
print(np.linalg.solve(mat,product))
print('-----')

print('')
print(np.linalg.inv(mat))

[1. 2. 3.]
-----

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [ ]:
#matrix algebra equation
# wx=c
# straigh line in compact form
w=np.array([[1,2],[2,1]])
x=np.array([[2,5],[6,5]])
print(w)
print('')
print(x)
print('')
c=np.matmul(w,x)
print(c)
print('')

print(np.linalg.solve(c,w))
print('')
()
print(x)

[[1 2]
 [2 1]]

[[2 5]
 [6 5]]

[[14 15]
 [10 15]]

[[-0.25  0.25]
 [ 0.3  -0.1 ]]

[[2 5]
 [6 5]]


In [ ]:
# we can find the unique values in an array
# numpy arrays of same data type
# order is not maintained after unique
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [ ]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(10,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.11332318 0.97505097 0.39267231 0.68056981 0.58833069]
 [0.33289739 0.05766066 0.71481689 0.46038447 0.25172813]
 [0.85787899 0.44187066 0.50119983 0.89367272 0.37600898]
 [0.66077234 0.51530142 0.34395638 0.90401175 0.81761893]
 [0.92502019 0.30022931 0.9319293  0.86948794 0.69464586]
 [0.87514339 0.21953694 0.60546275 0.97862493 0.52194626]
 [0.25965607 0.76064909 0.68510078 0.67304159 0.98601928]
 [0.21817708 0.84742014 0.48193704 0.14261088 0.2921156 ]
 [0.68316087 0.93894436 0.62451911 0.78039421 0.06810986]
 [0.63611116 0.33955875 0.76699764 0.70538789 0.21610022]]

[[ 0.74360158 -1.12160332 -0.14130103 -1.25070317  0.55357132]
 [-1.61941638  0.76588928 -1.08838054  0.040761   -1.88937164]
 [ 1.01812605  0.28637878 -2.50166225  0.4835328   0.12824165]
 [-0.67570839 -0.44461873 -0.36682834 -0.47632615 -0.57916028]
 [-0.4321497   1.12161413 -0.26386327  0.2680105  -1.30710877]
 [ 0.71988128 -1.82068339 -0.59536476 -0.03769028 -0.76544595]
 [-0.22186235  1.09685772 -1.1364208  -2

In [ ]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat))
print('')
print(np.mean(rand_mat2))
print(np.std(rand_mat2))

0.5781552999019532
0.2703822664906112

-0.3610088428721301
0.9891549310145855


In [ ]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.05766065929375874
1.4765957712598379


In [ ]:
# break here for next video!

In [ ]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.92504246 -0.83847545  0.06324878  0.96495675  1.41793252  1.1269297
 -0.75149436 -0.55797284 -1.13274969  1.36134095 -3.87807636  0.62812195
  1.11981277 -0.73036735 -0.60358246 -0.05127811 -0.64768246  1.51661138
  2.15316026]
-0.751494364858209


In [ ]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 1.41793252  1.1269297  -0.75149436 -0.55797284 -1.13274969]


In [ ]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.92504246  0.96495675 -0.75149436  1.36134095  1.11981277]


In [ ]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.341003   0.7980109  0.35265991 0.13709951 0.35390207]
 [0.92967945 0.37682662 0.33297276 0.5593009  0.77275219]
 [0.72377976 0.82568458 0.04335267 0.53624905 0.6807291 ]
 [0.73003729 0.48088037 0.20864757 0.25829545 0.33587798]
 [0.06856032 0.01997288 0.44049428 0.50464566 0.47793605]
 [0.30145908 0.10102702 0.41820826 0.28368781 0.6706236 ]
 [0.41484626 0.11738572 0.85617013 0.23113101 0.03723328]
 [0.17604646 0.1891594  0.08408086 0.6800127  0.19601956]
 [0.44987304 0.32493667 0.81867784 0.66106742 0.70488326]
 [0.89364417 0.17085551 0.17055857 0.2029677  0.66412681]]
0.332972759314482
0.332972759314482


In [ ]:
# slicing comes into picture in numpy arrays as well
print(rand_mat[0:2,1:3])

[[0.97505097 0.39267231]
 [0.05766066 0.71481689]]


In [ ]:
# let's change some values in an array!
print(rand_vec)  
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

NameError: ignored

In [ ]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.11332318 0.97505097 0.39267231 0.68056981 0.58833069]
 [0.33289739 0.05766066 0.71481689 0.46038447 0.25172813]
 [0.85787899 0.44187066 0.50119983 0.89367272 0.37600898]
 [0.66077234 0.51530142 0.34395638 0.90401175 0.81761893]
 [0.92502019 0.30022931 0.9319293  0.86948794 0.69464586]
 [0.87514339 0.21953694 0.60546275 0.97862493 0.52194626]
 [0.25965607 0.76064909 0.68510078 0.67304159 0.98601928]
 [0.21817708 0.84742014 0.48193704 0.14261088 0.2921156 ]
 [0.68316087 0.93894436 0.62451911 0.78039421 0.06810986]
 [0.63611116 0.33955875 0.76699764 0.70538789 0.21610022]]

[[0.11332318 0.97505097 0.39267231 0.68056981 0.58833069]
 [0.33289739 0.05766066 0.71481689 0.         0.        ]
 [0.85787899 0.44187066 0.50119983 0.         0.        ]
 [0.66077234 0.51530142 0.34395638 0.90401175 0.81761893]
 [0.92502019 0.30022931 0.9319293  0.86948794 0.69464586]
 [0.87514339 0.21953694 0.60546275 0.97862493 0.52194626]
 [0.25965607 0.76064909 0.68510078 0.67304159 0.98601928]
 [0.21817708

In [ ]:
# POINTER REFERENCE
# WIERD REFERENCE
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.11332318 0.97505097 0.39267231]
 [0.33289739 0.05766066 0.71481689]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [ ]:
print(rand_mat)

[[3.         3.         3.         0.68056981 0.58833069]
 [3.         3.         3.         0.         0.        ]
 [0.85787899 0.44187066 0.50119983 0.         0.        ]
 [0.66077234 0.51530142 0.34395638 0.90401175 0.81761893]
 [0.92502019 0.30022931 0.9319293  0.86948794 0.69464586]
 [0.87514339 0.21953694 0.60546275 0.97862493 0.52194626]
 [0.25965607 0.76064909 0.68510078 0.67304159 0.98601928]
 [0.21817708 0.84742014 0.48193704 0.14261088 0.2921156 ]
 [0.68316087 0.93894436 0.62451911 0.78039421 0.06810986]
 [0.63611116 0.33955875 0.76699764 0.70538789 0.21610022]]


In [ ]:
# TO NULLIFY POINTER REFERENCE
# WE USE .COPY COMMAND

sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.68056981 0.58833069]
 [3.         3.         3.         0.         0.        ]
 [0.85787899 0.44187066 0.50119983 0.         0.        ]
 [0.66077234 0.51530142 0.34395638 0.90401175 0.81761893]
 [0.92502019 0.30022931 0.9319293  0.86948794 0.69464586]
 [0.87514339 0.21953694 0.60546275 0.97862493 0.52194626]
 [0.25965607 0.76064909 0.68510078 0.67304159 0.98601928]
 [0.21817708 0.84742014 0.48193704 0.14261088 0.2921156 ]
 [0.68316087 0.93894436 0.62451911 0.78039421 0.06810986]
 [0.63611116 0.33955875 0.76699764 0.70538789 0.21610022]]


In [ ]:

# break here for next video

In [ ]:
# we can also access entries with logicals
# LOGICAL INDEXING
#
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0]) 

[ 0.89837845  1.59030342 -0.88535958  1.49757944  0.93383886  0.4323502
  0.07104523  0.27810367 -0.39092457  0.48294587  0.54346237 -0.94316503
 -0.27328931  1.83188723 -1.35297072]
[ True  True False  True  True  True  True  True False  True  True False
 False  True False]
[0.89837845 1.59030342 1.49757944 0.93383886 0.4323502  0.07104523
 0.27810367 0.48294587 0.54346237 1.83188723]


In [ ]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.74360158 -1.12160332 -0.14130103 -1.25070317  0.55357132]
 [-1.61941638  0.76588928 -1.08838054  0.040761   -1.88937164]
 [ 1.01812605  0.28637878 -2.50166225  0.4835328   0.12824165]
 [-0.67570839 -0.44461873 -0.36682834 -0.47632615 -0.57916028]
 [-0.4321497   1.12161413 -0.26386327  0.2680105  -1.30710877]
 [ 0.71988128 -1.82068339 -0.59536476 -0.03769028 -0.76544595]
 [-0.22186235  1.09685772 -1.1364208  -2.02898438 -0.04750979]
 [-2.27741793  0.27133992 -0.30824529 -0.44727459  1.45212813]
 [-1.1750793   1.41702746 -1.33091826  1.47659577 -0.82786039]
 [-0.84386725 -0.47758961  0.74734704 -0.5319584  -1.60897189]]
[0.74360158 0.55357132 0.76588928 0.040761   1.01812605 0.28637878
 0.4835328  0.12824165 1.12161413 0.2680105  0.71988128 1.09685772
 0.27133992 1.45212813 1.41702746 1.47659577 0.74734704]


In [ ]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 0.89837845  1.59030342 -0.88535958  1.49757944  0.93383886  0.4323502
  0.07104523  0.27810367 -0.39092457  0.48294587  0.54346237 -0.94316503
 -0.27328931  1.83188723 -1.35297072]

[-5.         -5.         -0.88535958 -5.         -5.          0.4323502
  0.07104523  0.27810367 -0.39092457  0.48294587 -5.         -0.94316503
 -0.27328931 -5.         -1.35297072]


In [ ]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [ ]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [ ]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

In [ ]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

In [ ]:
# we can also save/load as text files...but only single variables...but only one variables we could store
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

# New section